// subset of Music Macro Language

Commands ::= Command

Command ::= SetLength | SetOctave | SetScale | SetRest // notes
    | IncreaseOctave | DecreaseOctave                   // change octave relatively

SetLength ::= 'l' Length
SetOctave ::= 'o' Octave
SetScale  ::=  Scale ('+' | '-')? Length? Dot*
SetRest   ::= 'r' Length? Dot*
IncreaseOctave ::= '<'
DecreaseOctave ::= '>'

// Number
Length ::= HexNumber | DecimalNumber
HexNumber ::= '0x' (DecimalNumber | Hex10to15)+
DecimalNumber ::= '0' | NonZeroNumber

// Constant
NonZeroNumber ::= '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9'
Hex10to15 ::= 'a' | 'b' | 'c' | 'd' | 'e' | 'f'
Scale ::= 'c' | 'd' | 'e' | 'f' | 'g' | 'a' | 'b'
Sharp ::= '#'
Flat ::= 'b'
Octave ::= '2' | '3' | '4' | '5' | '6' | '7' | '8'
Dot ::= '.' // 付点
