/* Generated By:JJTree: Do not edit this line. ASTDecimalNumber.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=mml2mid.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mml2mid.parser;

public
class ASTDecimalNumber extends SimpleNode {
  public ASTDecimalNumber(int id) {
    super(id);
  }

  public ASTDecimalNumber(MmlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MmlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d1e3f0880eeb374ea1481f24a64e7f6c (do not edit this line) */
