/* Generated By:JJTree: Do not edit this line. ASTDecreaseOctave.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mml2mid.parser;

public
class ASTDecreaseOctave extends SimpleNode {
  public ASTDecreaseOctave(int id) {
    super(id);
  }

  public ASTDecreaseOctave(MmlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MmlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ac6678e422c49ddc3fb37056353db46e (do not edit this line) */
