/* Generated By:JJTree: Do not edit this line. ASTMMLCommands.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=mml2mid.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mml2mid.parser;

public
class ASTMMLCommands extends SimpleNode {
  public ASTMMLCommands(int id) {
    super(id);
  }

  public ASTMMLCommands(MmlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MmlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7693ed46e0660ea41bffb016162bf876 (do not edit this line) */
