/* Generated By:JJTree: Do not edit this line. ASTSetScale.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=mml2mid.expr.BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mml2mid.parser;

public
class ASTSetScale extends SimpleNode {
  public ASTSetScale(int id) {
    super(id);
  }

  public ASTSetScale(MmlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MmlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=997dddc39fcda4231c90f2393d4c9661 (do not edit this line) */
