/* Generated By:JJTree: Do not edit this line. ASTSetOctave.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package mml2mid.parser;

public
class ASTSetOctave extends SimpleNode {
  public ASTSetOctave(int id) {
    super(id);
  }

  public ASTSetOctave(MmlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MmlParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=19dd06c7d5ff017bf6da7757d1e7a756 (do not edit this line) */
