/* Generated By:JavaCC: Do not edit this line. ExprParserTreeConstants.java Version 6.0_1 */
package codezine.expr.parser;

public interface ExprParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADD = 2;
  public int JJTSUB = 3;
  public int JJTINTEGER = 4;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Add",
    "Sub",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=bb522ed23344cfa625df50fd9da06763 (do not edit this line) */
