/* Generated By:JJTree&JavaCC: Do not edit this line. MmlParserConstants.java */
package mml2mid.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MmlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NumberZeroToken = 5;
  /** RegularExpression Id. */
  int NonZeroNumberToken = 6;
  /** RegularExpression Id. */
  int Hex10to15Token = 7;
  /** RegularExpression Id. */
  int HexNumberPrefixToken = 8;
  /** RegularExpression Id. */
  int OctaveToken = 9;
  /** RegularExpression Id. */
  int ScaleToken = 10;
  /** RegularExpression Id. */
  int DotToken = 11;
  /** RegularExpression Id. */
  int LengthCommandToken = 12;
  /** RegularExpression Id. */
  int OctaveCommandToken = 13;
  /** RegularExpression Id. */
  int AccidentalsCommandToken = 14;
  /** RegularExpression Id. */
  int RestCommandToken = 15;
  /** RegularExpression Id. */
  int IncreaseOctaveCommandToekn = 16;
  /** RegularExpression Id. */
  int DecreaseOctaveCommandToken = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"0\"",
    "<NonZeroNumberToken>",
    "<Hex10to15Token>",
    "\"0x\"",
    "<OctaveToken>",
    "<ScaleToken>",
    "\".\"",
    "\"l\"",
    "\"o\"",
    "<AccidentalsCommandToken>",
    "\"r\"",
    "\"<\"",
    "\">\"",
  };

}
