/* Generated By:JavaCC: Do not edit this line. MmlParserTreeConstants.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserTreeConstants
{
  public int JJTMMLCOMMANDS = 0;
  public int JJTVOID = 1;
  public int JJTSETOCTAVE = 2;
  public int JJTSETSCALE = 3;
  public int JJTSETREST = 4;
  public int JJTINCREASEOCTAVE = 5;
  public int JJTDECREASEOCTAVE = 6;
  public int JJTLENGTH = 7;
  public int JJTDECIMALNUMBER = 8;


  public String[] jjtNodeName = {
    "MMLCommands",
    "void",
    "SetOctave",
    "SetScale",
    "SetRest",
    "IncreaseOctave",
    "DecreaseOctave",
    "Length",
    "DecimalNumber",
  };
}
/* JavaCC - OriginalChecksum=1b2cafa051f94ec622aba0c50a172f05 (do not edit this line) */
