/* Generated By:JavaCC: Do not edit this line. MmlParserDefaultVisitor.java Version 6.0_1 */
package mml2mid.parser;

public class MmlParserDefaultVisitor implements MmlParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTStart node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=b045880617cb012ee2b0c3ef8f583620 (do not edit this line) */
