/* Generated By:JavaCC: Do not edit this line. MmlParserTreeConstants.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSETOCTAVE = 1;
  public int JJTSETSCALE = 2;
  public int JJTSETREST = 3;
  public int JJTINCREASEOCTAVE = 4;
  public int JJTDECREASEOCTAVE = 5;


  public String[] jjtNodeName = {
    "void",
    "SetOctave",
    "SetScale",
    "SetRest",
    "IncreaseOctave",
    "DecreaseOctave",
  };
}
/* JavaCC - OriginalChecksum=ed33e8205d40ebd0c9f49eafcd4cd79c (do not edit this line) */
