/* Generated By:JavaCC: Do not edit this line. MmlParserTreeConstants.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;


  public String[] jjtNodeName = {
    "Start",
    "void",
  };
}
/* JavaCC - OriginalChecksum=e0f6ceba81e05eec6026988f5ebfbd6d (do not edit this line) */
