/* Generated By:JavaCC: Do not edit this line. MmlParserVisitor.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTSetOctave node, Object data);
  public Object visit(ASTSetScale node, Object data);
  public Object visit(ASTSetRest node, Object data);
  public Object visit(ASTIncreaseOctave node, Object data);
  public Object visit(ASTDecreaseOctave node, Object data);
  public Object visit(ASTLength node, Object data);
  public Object visit(ASTDecimalNumber node, Object data);
}
/* JavaCC - OriginalChecksum=ff89712db5935d7522e464b2889124a5 (do not edit this line) */
