/* Generated By:JavaCC: Do not edit this line. MmlParserVisitor.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTSetOctave node, Object data);
  public Object visit(ASTSetScale node, Object data);
  public Object visit(ASTSetRest node, Object data);
  public Object visit(ASTIncreaseOctave node, Object data);
  public Object visit(ASTDecreaseOctave node, Object data);
}
/* JavaCC - OriginalChecksum=980f7c7ca312e035e02c8ec99a15d883 (do not edit this line) */
