/* Generated By:JavaCC: Do not edit this line. MmlParserVisitor.java Version 6.0_1 */
package mml2mid.parser;

public interface MmlParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTMMLCommands node, Object data);
  public Object visit(ASTSetOctave node, Object data);
  public Object visit(ASTSetScale node, Object data);
  public Object visit(ASTSetRest node, Object data);
  public Object visit(ASTIncreaseOctave node, Object data);
  public Object visit(ASTDecreaseOctave node, Object data);
  public Object visit(ASTLength node, Object data);
  public Object visit(ASTDecimalNumber node, Object data);
}
/* JavaCC - OriginalChecksum=81f7c7ad1117e933698de9c1e499a65c (do not edit this line) */
